name=ShawirIOT
version=1.0.0
author=ShawirIOT Team
maintainer=admin@shawiriot.com
sentence=Official Arduino / ESP8266 / ESP32 library for ShawirIOT IoT Platform.
paragraph=Connect your microcontrollers (ESP8266, ESP32, Arduino WiFi) to ShawirIOT cloud or private server. Easily stream sensor data and receive remote controls with virtual pins just like Blynk.
category=Communication
url=http://localhost
architectures=*
includes=ShawirIOT.h
