name=ShawirIOT
version=1.1.0
author=Mushawir Odegoa (ShawirIOT Team)
maintainer=mushawirodegoa@gmail.com
sentence=Official Arduino / ESP8266 / ESP32 library for ShawirIOT IoT Platform.
paragraph=Connect your microcontrollers (ESP8266, ESP32, Arduino WiFi) to ShawirIOT cloud or private server. Easily stream sensor data and receive remote controls with virtual pins (V0-V255).
category=Communication
url=https://github.com/Shawir1312/IOT-LIBLARY
architectures=*
includes=ShawirIOT.h
