name=shawirWifi
version=2.0.17
author=Shawir (based on tzapu/tablatronix WiFiManager)
maintainer=Shawir
sentence=shawirWifi - WiFi Configuration manager with web captive portal for ESP8266/ESP32, customized by Shawir
paragraph=Library for configuring ESP8266/ESP32 WiFi credentials and custom parameters at runtime via captive portal. Customized version of WiFiManager with direct ShawirIOT integration.
category=Communication
url=https://github.com/Shawir1312/IOT-LIBLARY
architectures=esp8266,esp32
