name=ShawirWiFi
version=1.0.0
author=Mushawir
maintainer=Mushawir <admin@shawiriot.com>
sentence=Smart WiFi Manager & Captive Portal Library for ESP8266 and ESP32.
paragraph=Easily configure and auto-connect ESP8266 & ESP32 to WiFi via a sleek captive portal web page without hardcoding credentials in your sketch.
category=Communication
url=https://github.com/Shawir1312/IOT-SHAWIR
architectures=esp8266,esp32
includes=ShawirWiFi.h
